"""Project defaults."""

DEFAULT_CLOUD_URL = "https://cloud.tsinghua.edu.cn"
DEFAULT_CHUNK_SIZE_MB = 8
DEFAULT_SPLIT_SIZE_GB = 1.0
DEFAULT_RETRIES = 5
DEFAULT_RETRY_DELAY_SEC = 20.0
DEFAULT_CACHE_DIR = ".cache/thucloud"
DEFAULT_MAX_CACHE_GB = 20.0
DEFAULT_CONNECT_TIMEOUT_SEC = 15.0
DEFAULT_READ_TIMEOUT_SEC = 60.0
DEFAULT_UPLOAD_TIMEOUT_SEC = 600.0
DEFAULT_CACHE_TTL_HOURS = 24.0
